package mbcs

// Code generated by go-importconst DO NOT EDIT.
const CP_ACP = 0
const CP_MACCP = 2
const CP_OEMCP = 1
const CP_SYMBOL = 42
const CP_UTF7 = 65000
const CP_UTF8 = 65001
const MB_COMPOSITE = 2
const MB_ERR_INVALID_CHARS = 8
const MB_PRECOMPOSED = 1
const MB_USEGLYPHCHARS = 4
const WC_COMPOSITECHECK = 512
const WC_ERR_INVALID_CHARS = 128
const WC_NO_BEST_FIT_CHARS = 1024
